<a href="https://colab.research.google.com/github/Park-New-project/TIL/blob/main/%5BAI%5D_220930.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [ ]:
obj = Series(range(3), index=['a','b','c'])
obj

a    0
b    1
c    2
dtype: int64

In [ ]:
obj.values

array([0, 1, 2])

In [ ]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
idx = obj.index
idx

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
idx[0]

'a'

In [ ]:
idx[1]

'b'

In [ ]:
idx[1:]

Index(['b', 'c'], dtype='object')

In [ ]:
idx[2] = 'd' # 색인 객체는 수정을 할 수 없다

TypeError: ignored

In [ ]:
idx2 = pd.Index(np.arange(3))
idx2

Int64Index([0, 1, 2], dtype='int64')

In [ ]:
obj2 = Series([2.3,4.5,-4.1,3.5], index=['d','b','a','c'])
obj2

d    2.3
b    4.5
a   -4.1
c    3.5
dtype: float64

In [ ]:
obj3 = obj2.reindex(['a','b','c','d','e'])
obj3

a    0.0
b    1.0
c    NaN
d    3.0
e    4.0
dtype: float64

In [ ]:
obj_ = obj2.reindex(['a','b','c','d','e','f'], fill_value = 0.0)
obj_

a    0.0
b    1.0
c    0.0
d    3.0
e    4.0
f    0.0
dtype: float64

In [ ]:
df = DataFrame(np.arange(9))
df

0
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8

In [ ]:
df = DataFrame(np.arange(9).reshape(3,3))
df

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [ ]:
df = DataFrame(np.arange(9).reshape(3,3), index = ['a','b','d'], columns=['x','y','z'])
df

x  y  z
a  0  1  2
b  3  4  5
d  6  7  8

In [ ]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
df2 = df.reindex(['a','b','c','d'])
df2

x    y    z
a  0.0  1.0  2.0
b  3.0  4.0  5.0
c  NaN  NaN  NaN
d  6.0  7.0  8.0

In [ ]:
col=['x','y','w','z']
df3 = df2.reindex(columns=col)
df3

x    y   w    z
a  0.0  1.0 NaN  2.0
b  3.0  4.0 NaN  5.0
c  NaN  NaN NaN  NaN
d  6.0  7.0 NaN  8.0

In [ ]:
obj4 = Series(['blue','red','yellow'], index=[0,2,4])
obj4

0      blue
2       red
4    yellow
dtype: object

In [ ]:
obj4.reindex(range(6))

0      blue
1       NaN
2       red
3       NaN
4    yellow
5       NaN
dtype: object

In [ ]:
obj4.reindex(range(6), method='ffill')

0      blue
1      blue
2       red
3       red
4    yellow
5    yellow
dtype: object

In [ ]:
df3 = df.reindex(index=['a','b','c','d'], columns = col)
df3

x    y   w    z
a  0.0  1.0 NaN  2.0
b  3.0  4.0 NaN  5.0
c  NaN  NaN NaN  NaN
d  6.0  7.0 NaN  8.0

In [ ]:
obj = Series(np.arange(5),index=['a','b','c','d','e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [ ]:
obj2 = obj.drop('c')
obj2

a    0
b    1
d    3
e    4
dtype: int64

In [ ]:
obj # 원본 값은 변하지 않음

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [ ]:
obj3 = obj.drop(['c','b','d'])
obj3

a    0
e    4
dtype: int64

In [ ]:
obj # 원본 값은 변하지 않음

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [ ]:
obj4 = obj.drop('c')
obj4

a    0
b    1
d    3
e    4
dtype: int64

In [ ]:
df = DataFrame(np.arange(16).reshape(4,4),
                index = ['seoul', 'daejeon','daegu', 'busan'],
                columns=['one','two','three','four'])
df

one  two  three  four
seoul      0    1      2     3
daejeon    4    5      6     7
daegu      8    9     10    11
busan     12   13     14    15

In [ ]:
new_df = df.drop(['seoul','busan'])
new_df

one  two  three  four
daejeon    4    5      6     7
daegu      8    9     10    11

In [ ]:
df

one  two  three  four
seoul      0    1      2     3
daejeon    4    5      6     7
daegu      8    9     10    11
busan     12   13     14    15

In [ ]:
df.drop('three', axis=1)

one  two  four
seoul      0    1     3
daejeon    4    5     7
daegu      8    9    11
busan     12   13    15

In [ ]:
df

one  two  three  four
seoul      0    1      2     3
daejeon    4    5      6     7
daegu      8    9     10    11
busan     12   13     14    15

# Scraping
- 웹사이트 특정 정보를 추출

# Crawling
- 웹사이트의 정보를 정기적으로 추출


In [ ]:
import urllib.request

In [ ]:
url = "https://t1.daumcdn.net/daumtop_chanel/op/20200723055344399.png"
imgName = "daum.png"

In [ ]:
urllib.request.urlretrieve(url,imgName)
print("다운로드 완료")

다운로드 완료


- request.urlretrieve()
- request.urlopen()


In [ ]:
f = open("test1.txt", "w")

In [ ]:
f

<_io.TextIOWrapper name='test1.txt' mode='w' encoding='UTF-8'>

In [ ]:
f.write("test1.txt 에 들어갈 내용")
f.close()

In [ ]:
with open("test2.txt", "w") as f:
  f.write("test2.txt 에 들어갈 내용")

In [ ]:
import urllib.request
url = "https://t1.daumcdn.net/daumtop_chanel/op/20200723055344399.png"
imgName = "daum2.png"
downImg = urllib.request.urlopen(url).read()

In [ ]:
with open(imgName,"wb") as f:
  f.write(downImg)
print("다운로드 완료")

다운로드 완료


# 기상청 데이터 접근
- www.kma.go.kr
- 그러나, 데이터에 이미지가 너무 많기 때문에 XML 형태의 text형태로 확인 
- https://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp


# XML
- Web API

# HTML


In [ ]:
# <html>
#   <head>
#   </head>
#   <body>
#     <h1> 제목 </h1>
#   </body>
# </html>

In [ ]:
# 기상청 RSS 데이터 추출
import urllib.request
import urllib.parse

In [ ]:
rssUrl = "https://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp"
values = {
    'stnid' : '108'
}
type(values)

dict

In [ ]:
params = urllib.parse.urlencode(values)
url = rssUrl + "?" + params
print(url)

https://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp?stnid=108


In [ ]:
data = urllib.request.urlopen(url).read()
text = data.decode("utf-8")

print(text)

<?xml version="1.0" encoding="utf-8" ?>
<rss version="2.0">
<channel>
<title>기상청 육상 중기예보</title>
<link>http://www.kma.go.kr/weather/forecast/mid-term_01.jsp</link>
<description>기상청 날씨 웹서비스</description>
<language>ko</language>
<generator>기상청</generator>
<pubDate>2022년 10월 20일 (목)요일 18:00</pubDate>
 <item>
<author>기상청</author>
<category>육상중기예보</category>
<title>전국 육상 중기예보 - 2022년 10월 20일 (목)요일 18:00 발표</title>
<link>http://www.kma.go.kr/weather/forecast/mid-term_01.jsp</link>
<guid>http://www.kma.go.kr/weather/forecast/mid-term_01.jsp</guid>
<description>
	<header>
		<title>전국 육상중기예보</title>
		<tm>202210201800</tm>
		<wf><![CDATA[○ (강수) 24일(월)은 강원영동에 비가 오겠습니다.<br />○ (기온) 아침 기온은 3~13도로 오늘(20일, 아침최저기온 2~11도)과 비슷하거나 조금 높겠고, 낮 기온은 14~21도로 오늘(낮최고기온 18~24도)보다 낮겠습니다. <br /><br />* 이번 예보 기간에는 대기가 차차 건조해지겠으니, 산불 등 화재예방에 유의하기 바랍니다.]]></wf>
	</header>
	<body>
				

		<location wl_ver="3">
				<province>서울ㆍ인천ㆍ경기도</province>
				<city>서울</city>
				
				<data>
					<mode>A02</mode>
					<tmEf>2022-

# BeautifulSoup
- XML, HTML을 분석해주는 라이브러리

In [ ]:
from bs4 import BeautifulSoup

html = """
<html><body>
  <h1>스크레이핑 연습</h1>
  <p>웹 페이지를 분석하기</p>
  <p>데이터를 정제하기</p>
</body></html>
"""

# 1. 객체 생성
soup = BeautifulSoup(html, 'html.parser')
soup


<html><body>
<h1>스크레이핑 연습</h1>
<p>웹 페이지를 분석하기</p>
<p>데이터를 정제하기</p>
</body></html>

In [ ]:
# 2. 원하는 요소 접근
h1 = soup.html.body.h1
h1

<h1>스크레이핑 연습</h1>

In [ ]:
p1 = soup.html.body.p
p1

<p>웹 페이지를 분석하기</p>