<a href="https://colab.research.google.com/github/Park-New-project/TIL/blob/main/%5BAI%5D_220928.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive


# 정적 변수
- 모든 객체에서 하나만 생성
- 클래스 멤버
- 모든 객체가 하나의 변수를 공유한다
- 객체 생성 없이 사용 가능
- Static 어쩌구에서 잡힘

In [ ]:
# 정적변수
class Television:
  count = 0 # 정적변수 (클래스 멤버)
  def __init__(self):
    Television.count += 1
    print("init...")

In [ ]:
t = Television()
print(t.count)  # 클래스 내 정적 변수
print(Television.count) # 클래스 내 정적 변수

init...
7
7


# 정적 메소드
- @staticmethod

# 특수 메소드 (Special method)
- 덧셈, 뺄셈 등에 대하여 미리 정해져 있음

In [ ]:
# 정적 메소드
class Test:
  @staticmethod
  def show():
    print("show")
    

In [ ]:
Test.show() # 생성 전에도 사용 가능

show


In [ ]:
list1 = [1,2,3]
list2 = [1,2,3]
list1 + list2

[1, 2, 3, 1, 2, 3]

In [ ]:
# Member 클래스 만들기
'''
생성자 : 이름 나이 주소
인스턴스 변수 : 이름 나이 주소 (private)
'''

class Member:
    def __init__(self, name=None, age = 0, address=None):
        self.__name = name
        self.__age = age
        self.__address = address

    # setter
    def setName(self, name):
        self.__name = name

    def setAge(self, age):
        self.__age = age

    def setAddress(self, address):
        self.__address = address

    # getter
    def getName(self):
        return self.__name

    def getAge(self):
        return self.__age

    def getAddress(self):
        return self.__address
        

In [ ]:
mem = Member("kim", 20, "seoul")
print(mem)
print(mem.getName(),"",mem.getAge(),"",mem.getAddress())

kim  20  seoul


In [ ]:
mem2 = Member()
print(mem2)
mem2.setName("kang")
mem2.setAge(27)
mem2.setAddress("masan")

print(mem2.getName(),"",mem2.getAge(),"",mem2.getAddress())

kang  27  masan


In [ ]:
list1 = [1,2,3]
list1.append(10)
print(list1)

[1, 2, 3, 10]


[]
<class 'list'>


In [ ]:
# 객체 배열 (리스트)
mem = []
print(mem)
print(type(mem))

mem.append(Member("kim"))
mem.append(Member("Park"))
mem.append(Member("Kang"))
print(mem)
print(mem[0].getName())
print(mem[1].getName())
print(mem[2].getName())

[]
<class 'list'>
[<__main__.Member object at 0x7f83495d4490>, <__main__.Member object at 0x7f83495d4610>, <__main__.Member object at 0x7f83495d4510>]
kim
Park
Kang


# Numpy
- 벡터 배열에서 데이터 정제, 개조, 부분집합, 필터링, 변형, 정렬, 원소, 집합 ...

# 선형대수 
# data 종류
1. scalar : 점. 실수 하나로 이루어진 것
2. vector: 선. 여러 개의 숫자가 특정한  순서로 모여있는 데이터 레코드
3. matrix : 면. vector 집합
4. tensor : 입체. 같은 크기의 행렬이 모여있는 것

In [ ]:
import numpy

data1 = [1,2,3,4,5]
print(data1)

[1, 2, 3, 4, 5]


In [ ]:
arr1 = numpy.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [ ]:
import numpy as np

data2 = [1,2,3,4,5,6,7]
arr2 = np.array(data2)

In [ ]:
arr2.shape

(7,)

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
arr3 = np.array(data2, dtype='int16')
arr3

array([1, 2, 3, 4, 5, 6, 7], dtype=int16)

In [ ]:
arr3.shape

(7,)

In [ ]:
arr3.dtype

dtype('int16')

In [ ]:
type(arr3)

numpy.ndarray

In [ ]:
list1 = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
]

In [ ]:
arr4 = np.array(list1)

In [ ]:
arr4.shape

(4, 3)

In [ ]:
arr4.dtype

dtype('int64')

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 같은 위치의 요소들끼리 덧셈
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

arr2 = np.array([[10,11,12],[13,14,15]])
print(arr2)

arr1+arr2

[[1 2 3]
 [4 5 6]]
[[10 11 12]
 [13 14 15]]


array([[11, 13, 15],
       [17, 19, 21]])

In [ ]:
[[1,2,3],[4,5,6]] + [[10,11,12],[13,14,15]]

[[1, 2, 3], [4, 5, 6], [10, 11, 12], [13, 14, 15]]

In [ ]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
[[1,2,3],[4,5,6]] * 10

[[1, 2, 3],
 [4, 5, 6],
 [1, 2, 3],
 [4, 5, 6],
 [1, 2, 3],
 [4, 5, 6],
 [1, 2, 3],
 [4, 5, 6],
 [1, 2, 3],
 [4, 5, 6],
 [1, 2, 3],
 [4, 5, 6],
 [1, 2, 3],
 [4, 5, 6],
 [1, 2, 3],
 [4, 5, 6],
 [1, 2, 3],
 [4, 5, 6],
 [1, 2, 3],
 [4, 5, 6]]

In [ ]:
# 슬라이싱 : 부분 리스트
arr1= np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr1[5:]

array([5, 6, 7, 8, 9])

In [ ]:
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [ ]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
arr2[2][3]

12

In [ ]:
arr2[2,3]

12

In [ ]:
arr2[2:]

array([[ 9, 10, 11, 12]])

In [ ]:
arr2[2,2:]

array([11, 12])

In [ ]:
arr2[1:2,1:3]

array([[6, 7]])

In [ ]:
arr2[0,2:]

array([3, 4])

In [ ]:
arr2[:,3]

array([ 4,  8, 12])

In [ ]:
arr2[1:,:2]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
arr2[:2,1:3]

array([[2, 3],
       [6, 7]])

In [ ]:
arr = np.full((2,3),10)
arr

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
arr2 = np.eye(4)
arr2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
arr3 = np.eye(4, M=5)
arr3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
arr4 = np.eye(4, M=5, k=1)
arr4

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr5 = np.eye(4, M=5, k=-2)
arr5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [ ]:
arr1 = np.array(range(20))
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr2 = np.array(range(20)).reshape((5,4))
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
arr3 = np.array(range(20))
arr3.reshape((4,5))
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr3 = np.array(range(20))
arr3 = arr3.reshape((4,5))
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
list1 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
print(list1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
arr = np.array(list1) # 넘파이 배열
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [ ]:
arr[:,2:3]

array([[3],
       [6],
       [9]])

In [ ]:
arr[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [ ]:
arr[0:2,1:2]

array([[2],
       [5]])

In [ ]:
arr[1:2,1:]

array([[5, 6]])

In [ ]:
# 정수 인덱싱
list1 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
a = np.array(list1)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[[0,2],[1,3]]

array([ 2, 12])