<a href="https://colab.research.google.com/github/Park-New-project/TIL/blob/main/%5BAI%5D_221026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 오차 역전파
- 은닉층에 포함된 가중치를 업데이트 하는 방법
- 경사하강법을 인공신경망에 적용
- 스스로 가중치를 조절하는 학습을 실현

1. 임의의 초기 가중치 부여하고 yout을 계산
2. 계산 결과 예측값과 실제값의 오차를 구함
3.  경사하강법을 이용해서 바로 앞의 가중치를 오차가 작아지는 방향으로 수정
4. 위의 과정을 오차가 더이상 줄어들지 않을 때까지 반복

1. 환경변수 지정 - 임의의 가중치, 편향, 학습률, 에폭 등을 지정함
2. 신경망 실행
3. 결과 -> 실제값과 비교
4. 반복 -> 출력층의 가중치 수정 -> 은닉층 가충치 수정 -> 2. 실행으로
5. 결과 출력

# 다층 퍼셉트론
- 인공 신경망과 구조는 동일하지만 확정된 가중치와 편향을 기준으로 평가하기 때문에 인공신경망과 다르다.
- 인공신경망은 임의의 가중치와 편향을 가지고 최적의 가중치와 편향을 찾는다. (반복을 통해 오차 역전파)

# 시그모이드 함수 기울기 소실문제
- 층이 깊어지면 출력층에서 시작된 가중치 없데이트가 처음 층까지 전달 되지 않는 현상이 생긴다. (시그모이드 함수 특성 때문임)
- 시그모이드 함수의 미분값이 0.25가 넘지 않음
- 다른 활성화 함수 도입하여 해결 
- 렐루 함수 : 미분해도 기울기 소실 X
- 하이퍼블릭 탄젠트 함수 : -1 ~ 1
- 소프트 플러스 함수 : 렐루 함수 보완
- 소프트 맥스 함수

# 확률적 경사하강법 (SGD)
- 경사하강법은 전체 데이터를 미분하므로 속도가 느리다.
- 확률적 경사하강법은 랜덤하게 추출한 일부 데이터만 사용해 빠르고 자주 업데이트 가능하다.
- 진폭이 크고 불안정하지만 속도가 확연히 빠르고 최적 해에 근사한 값을 찾아낸다는 장점이 있다.

# 모멘텀
- 가중치와 편향 변경시 고려 사항 -> 미분(변화량), 방향
- 관성의 방향을 고려해 지그재그 폭이 좀 줄어든다.

# 고급 경사하강법
1. 확률적 경사 하강법 (SGD) : 랜덤하게 데이터를 추출해서 미분 더 빨리 자주 업데이트 가능 -> 속도 개선
2. 모멘텀 (Momentum) : 관성과 방향을 고려해 진동과 폭을 줄이는 효과 -> 정확도 개선
3. 네스테로프 모멘텀 (NAG) : 모멘텀이 이동시킬 방향으로 미리 이동해서 그레디언트를 계산. 불필요한 이동 줄이는 효과 -> 정확도 개선
4. 아다그라드 (Adagrad) : 변수의 업데이트 잦으면 학습률을 적게 이동. 보폭을 조절 -> 보폭 크기 개선
5. 알엠에스프롭 (RMSprop) : 아파그라드의 보폭의 민감도를 개선 -> 보폭 크기 개선
6. 아담 (Adam) : Momentum 과 RMSprop 합친 방법
-> 가장 많이 사용, 정확도와 보폭 크기를 개선



# 딥러닝 모델 

In [1]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive


In [2]:
!pip install tensorflow==2.6.1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
!pip install keras==2.6

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
import numpy as np

In [5]:
Data_set = np.loadtxt("/content/gdrive/MyDrive/Colab/data/ThoraricSurgery.csv", delimiter= ",")
Data_set

array([[293.  ,   1.  ,   3.8 , ...,   0.  ,  62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88, ...,   0.  ,  60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19, ...,   0.  ,  66.  ,   1.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,  62.  ,   0.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,  58.  ,   1.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,  49.  ,   0.  ]])

In [6]:
print(Data_set.shape)
print(Data_set.dtype)

(470, 18)
float64


# ML 구성요소 (지도 학습)
1. 데이터 준비 : train data, valid data, test data
2. 모델 표현방법 : SVM, KNN, DL
3. 모델 평가 -> 정확도

In [7]:
x = Data_set[:,0:17]
x

array([[293.  ,   1.  ,   3.8 , ...,   1.  ,   0.  ,  62.  ],
       [  1.  ,   2.  ,   2.88, ...,   1.  ,   0.  ,  60.  ],
       [  8.  ,   2.  ,   3.19, ...,   1.  ,   0.  ,  66.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,   0.  ,  62.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,   0.  ,  58.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,   0.  ,  49.  ]])

In [8]:
x.shape

(470, 17)

In [9]:
y = Data_set[:,17]
y

array([0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0.

In [10]:
y.shape

(470,)

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# 딥러닝 모델 생성 (구조를 구성)
model = Sequential()
model

In [14]:
model.add(Dense(30, input_dim=17, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x,y,epochs=100, batch_size=10)

Epoch 1/100
47/47 [==============================] - 1s 3ms/step - loss: 0.6761 - accuracy: 0.6468
Epoch 2/100
47/47 [==============================] - 0s 2ms/step - loss: 0.6018 - accuracy: 0.8511
Epoch 3/100
47/47 [==============================] - 0s 2ms/step - loss: 0.5444 - accuracy: 0.8511
Epoch 4/100
47/47 [==============================] - 0s 2ms/step - loss: 0.4939 - accuracy: 0.8511
Epoch 5/100
47/47 [==============================] - 0s 2ms/step - loss: 0.4475 - accuracy: 0.8511
Epoch 6/100
47/47 [==============================] - 0s 3ms/step - loss: 0.4280 - accuracy: 0.8511
Epoch 7/100
47/47 [==============================] - 0s 2ms/step - loss: 0.4226 - accuracy: 0.8511
Epoch 8/100
47/47 [==============================] - 0s 2ms/step - loss: 0.4218 - accuracy: 0.8511
Epoch 9/100
47/47 [==============================] - 0s 2ms/step - loss: 0.4212 - accuracy: 0.8511
Epoch 10/100
47/47 [==============================] - 0s 2ms/step - loss: 0.4210 - accuracy: 0.8511
Epoch 11/

In [16]:
model.add(Dense(30, input_dim=17, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
model.fit(x,y,epochs=100, batch_size=10)

Epoch 1/100
47/47 [==============================] - 1s 2ms/step - loss: 0.2298 - accuracy: 0.7532
Epoch 2/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1843 - accuracy: 0.8511
Epoch 3/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1527 - accuracy: 0.8511
Epoch 4/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1363 - accuracy: 0.8511
Epoch 5/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1299 - accuracy: 0.8511
Epoch 6/100
47/47 [==============================] - 0s 3ms/step - loss: 0.1280 - accuracy: 0.8511
Epoch 7/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1272 - accuracy: 0.8511
Epoch 8/100
47/47 [==============================] - 0s 3ms/step - loss: 0.1269 - accuracy: 0.8511
Epoch 9/100
47/47 [==============================] - 0s 2ms/step - loss: 0.1268 - accuracy: 0.8511
Epoch 10/100
47/47 [==============================] - 0s 3ms/step - loss: 0.1268 - accuracy: 0.8511
Epoch 11/

In [17]:
model.add(Dense(30, input_dim=17, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x,y,epochs=100, batch_size=10)

Epoch 1/100
47/47 [==============================] - 1s 3ms/step - loss: 0.6802 - accuracy: 0.6426
Epoch 2/100
47/47 [==============================] - 0s 2ms/step - loss: 0.6197 - accuracy: 0.8511
Epoch 3/100
47/47 [==============================] - 0s 2ms/step - loss: 0.5591 - accuracy: 0.8511
Epoch 4/100
47/47 [==============================] - 0s 3ms/step - loss: 0.4953 - accuracy: 0.8511
Epoch 5/100
47/47 [==============================] - 0s 3ms/step - loss: 0.4484 - accuracy: 0.8511
Epoch 6/100
47/47 [==============================] - 0s 3ms/step - loss: 0.4283 - accuracy: 0.8511
Epoch 7/100
47/47 [==============================] - 0s 2ms/step - loss: 0.4226 - accuracy: 0.8511
Epoch 8/100
47/47 [==============================] - 0s 3ms/step - loss: 0.4218 - accuracy: 0.8511
Epoch 9/100
47/47 [==============================] - 0s 3ms/step - loss: 0.4217 - accuracy: 0.8511
Epoch 10/100
47/47 [==============================] - 0s 3ms/step - loss: 0.4214 - accuracy: 0.8511
Epoch 11/

- 구조 작성 Sequential
- 층을 설정 Dense()
- tensorflow는 입력층이 없다. 
- 은닉층은 input_dim 속성을 갖는다.
- 오차함수 loss
- 최적화 함수 optimizer
- 평가 기준 metrics
- 기계 학습 fit
- 샘플 수 batch size

In [18]:
model.evaluate(x,y) # 평가

15/15 [==============================] - 1s 3ms/step - loss: 0.4209 - accuracy: 0.8511


[0.42088425159454346, 0.8510638475418091]

In [20]:
print("정확도 : %.2f"%(model.evaluate(x,y)[1]*100)) # 정확도

15/15 [==============================] - 0s 5ms/step - loss: 0.4209 - accuracy: 0.8511
정확도 : 85.11
